#%RAML 1.0
title: dpm-sl-bankofcanada
protocols:
  - HTTP

/exchange-rate-summary:
  get:
    queryParameters:
      startDate?:
        example: 2022-10-24
        type: date-only | nil
      endDate?:
        example: 2022-10-24
        type: date-only | nil
      seriesNames?:
        example: FXUSDCAD
        type: string | nil
      format?:
        type: string | nil
        example: json xml csv
    responses:
      "200":
        body:
          application/json:
            examples:
              output: {
    "terms": {
        "url": "https://www.bankofcanada.ca/terms/"
    },
    "seriesDetail": {
        "FXUSDCAD": {
            "label": "USD/CAD",
            "description": "US dollar to Canadian dollar daily exchange rate",
            "dimension": {
                "key": "d",
                "name": "date"
            }
        }
    },
    "observations": [
        {
            "d": "2019-05-09",
            "FXUSDCAD": {
                "v": "1.3483"
            }
        },
        {
            "d": "2019-05-10",
            "FXUSDCAD": {
                "v": "1.3418"
            }
        },
        {
            "d": "2019-05-13",
            "FXUSDCAD": {
                "v": "1.3457"
            }
        },
        {
            "d": "2019-05-14",
            "FXUSDCAD": {
                "v": "1.3469"
            }
        }
    ]
}
mediaType:
  - application/json
